[package]
name = "rust-concepts"
version = "0.1.0"
edition = "2021"

[dependencies]
time = "=0.3.41"
actix-web = "4"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
xitca-web = { version = "*" , features = ["logger"]}